version: '3.7'

services:
  db:
    image: mariadb:10.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: IVP
      MYSQL_USER: IVP
      MYSQL_PASSWORD: ivp
      MYSQL_ROOT_PASSWORD: ivp
    network_mode: host
    volumes:
      - "mysql_db:/var/lib/mysql"
      - ./mysql/install_db.sh:/docker-entrypoint-initdb.d/install_db.sh
      - ./mysql/localhost.sql:/docker-entrypoint-initdb.d/localhost.sql

volumes:
    mysql_db:
